apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    name: voting-app-deployment
    app: voting-app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      ame: voting-app-pod
      app: voting-app-example
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: voting-app-example
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
