apiVersion: v1
kind: Service
metadata:
  name: result-app-sevice
spec:
  type: LoadBalancer
  selector:
    name: result-app-pod
    app: voting-app-deployment
  ports:
    - port: 80
      targetPort: 80