apiVersion: v1
kind: Service
metadata:
  name: voting-app-sevice
spec:
  type: LoadBalancer
  selector:
    name: voting-app-pod
    app: voting-app-example
  ports:
    - port: 80
      targetPort: 80